# Generated by Django 4.2.3 on 2023-07-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_shopitem_shoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shoes',
            new_name='ShopItem',
        ),
    ]
