# Generated by Django 4.2.3 on 2023-07-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shop_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_item', to='cart.shopitem'),
        ),
    ]
