# Generated by Django 4.2.3 on 2023-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_completed_alter_cartitem_shop_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
