# Generated by Django 4.2.3 on 2023-07-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_shopitem_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
